INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Aaron', 'Abaca', 1, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Abel', 'Abad', 2, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Abelardo', 'Alcala', 3, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Abigail', 'Alvarez', 4, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Abril', 'Abadia', 5, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Ada', 'Abalde', 6, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Adalberto', 'Abalo', 7, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Adan', 'Abalos', 8, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Adela', 'Abal', 9, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Adelaida', 'Aban', 10, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Adelina', 'Abanades', 11, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Adelmo', 'Abanco', 12, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Adolfo', 'Abando', 13, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Adrian', 'Abanto', 14, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Adriano', 'Abar', 15, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Agata', 'Abarca', 16, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Agueda', 'Abarzua', 17, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Agustin', 'Abarzuza', 18, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Aida', 'Abascal', 19, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Ainara', 'Abellan', 20, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Baldomero', 'Baamonde', 21, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Baltasar', 'Babier', 22, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Barack', 'Babio', 23, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Barbara', 'Bable', 24, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Bartolome', 'Babot', 25, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Basilio', 'Baca', 26, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Bautista', 'Bacaicoa', 27, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Beatriz', 'Bacardi', 28, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Belen', 'Baccela', 29, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Belinda', 'Baceiredo', 30, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Beltran', 'Becener', 31, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Benigno', 'Bach', 32, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Benito', 'Bachiller', 33, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Benjamin', 'Bachs', 34, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Berenice', 'Baciu', 35, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Bernabe', 'Back', 36, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Bernardino', 'Baco', 37, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Bernardina', 'Baca', 38, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Berta', 'Badala', 39, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Bianca', 'Badal', 40, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Camelia', 'Badel', 41, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Camila', 'Badia', 42, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Candido', 'Badillo', 43, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Caridad', 'Badimon', 44, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Carina', 'Badiola', 45, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Carlos', 'Badolato', 46, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Carla', 'Badorrey', 47, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Carmelo', 'Baecke', 48, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Carmen', 'Baeder', 49, '1990-01-01');
INSERT INTO `high-school`.`Student` (`student_first_name`, `student_last_name`, `registration_number`, `student_date_of_birth`) VALUES ('Celina', 'Baella', 50, '1990-01-01');

INSERT INTO `high-school`.`Teacher` (`first_name`, `last_name`, `date_of_birth`, `teacher_id`) VALUES ('Tadeo', 'Talleda', '1970-10-12', 'T1');
INSERT INTO `high-school`.`Teacher` (`first_name`, `last_name`, `date_of_birth`, `teacher_id`) VALUES ('Teo', 'Taibo', '1970-12-12', 'T2');
INSERT INTO `high-school`.`Teacher` (`first_name`, `last_name`, `date_of_birth`, `teacher_id`) VALUES ('Telmo', 'Tamez', '1970-12-24', 'T3');

INSERT INTO `high-school`.`Course` (`course_name`, `hours_by_week`, `schedule_time`, `Teacher_id`) VALUES ('algebra', 1, 5, 'T1');
INSERT INTO `high-school`.`Course` (`course_name`, `hours_by_week`, `schedule_time`, `Teacher_id`) VALUES ('biology', 2, 4, 'T2');
INSERT INTO `high-school`.`Course` (`course_name`, `hours_by_week`, `schedule_time`, `Teacher_id`) VALUES ('computer science', 3, 3, 'T3');
INSERT INTO `high-school`.`Course` (`course_name`, `hours_by_week`, `schedule_time`, `Teacher_id`) VALUES ('data communication', 4, 2, 'T1');
INSERT INTO `high-school`.`Course` (`course_name`, `hours_by_week`, `schedule_time`, `Teacher_id`) VALUES ('electronic', 5, 1, 'T2');

INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (1, 'algebra', 7, 7, 7, 1);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (2, 'algebra', 7, 7, 7, 3);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (3, 'algebra', 7, 7, 7, 3);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (4, 'algebra', 7, 7, 7, 4);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (5, 'algebra', 7, 7, 7, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (6, 'algebra', 7, 7, 7, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (7, 'algebra', 7, 7, 7, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (8, 'algebra', 7, 7, 7, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (9, 'algebra', 7, 7, 7, 9);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (10, 'algebra', 7, 7, 7, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (11, 'algebra', 7, 7, 7, 3);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (12, 'algebra', 7, 7, 7, 4);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (13, 'algebra', 7, 7, 7, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (14, 'algebra', 8, 8, 8, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (15, 'algebra', 8, 8, 8, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (16, 'algebra', 8, 8, 8, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (17, 'algebra', 8, 8, 8, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (18, 'algebra', 8, 8, 8, 9);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (19, 'algebra', 8, 8, 8, 9);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (20, 'algebra', 8, 8, 8, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (21, 'biology', 4, 5, 4, 1);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (22, 'biology', 3, 6, 4, 2);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (23, 'biology', 2, 6, 5, 3);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (24, 'biology', 4, 5, 6, 4);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (25, 'biology', 4, 4, 4, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (26, 'biology', 5, 5, 3, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (27, 'biology', 6, 4, 2, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (28, 'biology', 7, 6, 4, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (29, 'biology', 5, 7, 4, 9);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (30, 'biology', 4, 8, 5, 1);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (31, 'biology', 4, 7, 6, 2);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (32, 'biology', 5, 7, 7, 3);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (33, 'biology', 6, 5, 1, 4);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (34, 'biology', 7, 4, 1, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (35, 'biology', 7, 7, 2, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (36, 'biology', 5, 8, 3, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (37, 'biology', 4, 6, 4, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (38, 'biology', 5, 5, 5, 9);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (39, 'biology', 6, 4, 6, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (40, 'biology', 6, 6, 3, 4);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (1, 'computer science', 7, 7, 4, 3);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (3, 'computer science', 8, 8, 5, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (5, 'computer science', 6, 6, 3, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (7, 'computer science', 5, 5, 4, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (9, 'computer science', 6, 4, 5, 9);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (11, 'computer science', 6, 6, 3, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (13, 'computer science', 5, 5, 6, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (15, 'computer science', 7, 4, 4, 4);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (17, 'computer science', 8, 7, 3, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (19, 'computer science', 6, 7, 5, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (21, 'computer science', 6, 8, 7, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (23, 'computer science', 5, 6, 5, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (25, 'computer science', 6, 5, 4, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (27, 'computer science', 6, 4, 3, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (29, 'computer science', 5, 4, 4, 9);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (31, 'computer science', 6, 7, 6, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (33, 'computer science', 6, 8, 7, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (35, 'computer science', 8, 6, 5, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (37, 'computer science', 7, 8, 4, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (39, 'computer science', 6, 6, 3, 9);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (40, 'electronic', 8, 5, 4, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (41, 'electronic', 7, 7, 6, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (42, 'electronic', 6, 6, 4, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (43, 'electronic', 7, 5, 3, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (44, 'electronic', 7, 8, 4, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (45, 'electronic', 6, 8, 5, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (46, 'electronic', 7, 7, 6, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (47, 'electronic', 8, 6, 7, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (48, 'electronic', 7, 5, 8, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (49, 'electronic', 6, 4, 6, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (50, 'electronic', 7, 5, 5, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (1, 'electronic', 7, 6, 4, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (2, 'electronic', 6, 7, 3, 9);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (3, 'electronic', 8, 8, 4, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (4, 'electronic', 9, 9, 5, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (5, 'electronic', 7, 7, 6, 4);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (21, 'electronic', 5, 6, 7, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (22, 'electronic', 6, 5, 6, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (23, 'electronic', 5, 4, 5, 7);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (24, 'electronic', 6, 5, 4, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (2, 'data communication', 4, 4, 8, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (4, 'data communication', 5, 5, 9, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (6, 'data communication', 7, 6, 6, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (8, 'data communication', 5, 7, 5, 4);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (10, 'data communication', 4, 8, 4, 2);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (12, 'data communication', 9, 9, 7, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (14, 'data communication', 8, 5, 8, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (16, 'data communication', 4, 2, 9, 9);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (18, 'data communication', 5, 1, 5, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (20, 'data communication', 6, 4, 6, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (22, 'data communication', 2, 7, 5, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (24, 'data communication', 4, 8, 4, 4);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (26, 'data communication', 7, 5, 7, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (28, 'data communication', 8, 6, 8, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (30, 'data communication', 9, 9, 9, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (32, 'data communication', 4, 8, 6, 6);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (34, 'data communication', 5, 5, 5, 8);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (36, 'data communication', 6, 6, 4, 5);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (38, 'data communication', 7, 7, 7, 4);
INSERT INTO `high-school`.`Student_assist_Course` (`Student_registration_number`, `Course_name`, `first_partial`, `second_partial`, `third_partial`, `final`) VALUES (40, 'data communication', 8, 4, 8, 7);
